apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  labels:
    app: redis-password
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  REDISCLI_AUTH: "{{ .Values.auth.password }}"